### ISSUE TITLE
type 'GeoPoint' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by eagerashwani** [brandon-irl/CloudNextFlutterMapsDemo#1]
My firestore look like

![Screenshot (158)](https://user-images.githubusercontent.com/34451016/59407933-73619600-8dd0-11e9-88d9-1b56811a074c.png)

**Comment by brandon-irl** [comment]
You are putting your location in the wrong field. It should be named `location`:

![image](https://user-images.githubusercontent.com/4008993/59472421-5e0a5d00-8e0c-11e9-94d9-d1b77433fd1d.png)

**Comment by eagerashwani** [comment]
@brandon-irl 
# Thanks

**Comment by eagerashwani** [comment]
@brandon-irl , Is there any way how to get the rating ?

**Comment by brandon-irl** [comment]
Here is some documentation from Google on how to do that: https://developers.google.com/places/web-service/details#PlaceDetailsResults
